version: '3.8'
services:
  puextruder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Develoment
        restart: always
