version: '3.8'
services:
  puextruder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Develoment
    restart: always
